openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack WebApp
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of AquaTrack app
tags:
  - name: water
    description: Operations about AquaTrack.
  - name: user
    description: User operations.
servers:
  # - url: http://localhost:3000
  - url: https://aquatrack-webapp-backend.onrender.com
paths:
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/daily/:{date}:
    get:
      $ref: ../swagger/paths/water/daily/{date}/get.yaml
  /water/monthly/:{month}:
    get:
      $ref: ../swagger/paths/water/monthly/{month}/get.yaml
  /water/:{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml

  /users/total-users:
    get:
      $ref: ../swagger/paths/user/get-total-users.yaml
  /users/register:
    post:
      $ref: ../swagger/paths/user/register.yaml
  /users/login:
    post:
      $ref: ../swagger/paths/user/login.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/user/get-current.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/user/logout.yaml
  /users/refresh-tokens:
    post:
      $ref: ../swagger/paths/user/refresh.yaml
  /users/send-reset-email:
    post:
      $ref: ../swagger/paths/user/send-reset-email.yaml
  /users/reset-password:
    post:
      $ref: ../swagger/paths/user/reset-password.yaml
  /users/get-oauth-url:
    post:
      $ref: ../swagger/paths/user/get-oauth-url.yaml
  /users/verify-google-oauth:
    post:
      $ref: ../swagger/paths/user/verify-google-oauth.yaml
  /users/:{userId}:
    get:
      $ref: ../swagger/paths/user/{userId}/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
